version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations/000001_create_tables.up.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks:
      - default

  server:
    container_name: anti-bruteforce-app
    build: ./
    image: anti-bruteforce-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SERVER_TYPE: ${SERVER_TYPE}
    networks:
      - default
    volumes:
      - './:/src'

volumes:
  db:
    driver: local

networks:
  default:
    name: anti-bruteforce
